### PR TITLE
Update to Pubspec [system_info2: 3.0.1 => 3.0.2]

### PR DESCRIPTION
**Pull request by tsavo-at-pieces**
Updated to include system_info2: 3.0.2

### CODE REVIEW

**Comment by tsavo-at-pieces** [comment]
@bsutton Small ping on this. Changes were looking solid in system_info2!

**Comment by bsutton** [comment]
Will try to get to it this week end.

OnePub has just gone live and we start advertising next week so a little
busy at work:)

Https://OnePub.dev

**Comment by tsavo-at-pieces** [comment]
Awesome! We will definitely be a customer 🤝 Would love to chat some time about the insane stuff we are building with DCLI over at [Pieces for Developers](code.pieces.app) 

In Q2 we are launching a whole new suite of in IDE products powered by Googles Bard LLM... the awesome thing is that DCLI enabled us to AOT everything and we can serve these AOTs directly in our IntelliJ & VS Code Plugins eliminating the need for our core Pieces OS to be installed along side the plugins! 

We are a full time team of about 22 people (17 Eng & ML) and we write 90% of our code in dart! TLDR - we need OnePub.dev!

**Comment by bsutton** [comment]
Love to catch up.

I've got some big changes coming to dcli so it would be great to bounce
them off you.

I'm in GMT + 11 but pretty flexible if you want to suggest a time.

**Comment by tsavo-at-pieces** [comment]
You bet - hit me at my email and we can set it up!

***@***.***

I'll probs delete this comment later so it can't get scraped 😅

Looking forward to it!

-Tsavo

**Comment by bsutton** [comment]
Tsavo,
looks like github suppresses email addresses.

My email address is on my github profile if you want to email me directly.

**Comment by bsutton** [comment]
Released as 2.1.0

**Pull request closed without merging**
